version: '3.5'
services:
   mysql_test:
      image: mysql:latest
      container_name: horse_game_pathfinder_test_db
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: password
      ports:
         - 3306:3306