version: '3.5'
services:
   mysql-test:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: password
      ports:
         - 5613:3306